//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poolAdminMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarTimeRow
    {
        public int Id { get; set; }
        public Nullable<int> Lane1 { get; set; }
        public Nullable<int> Lane2 { get; set; }
        public Nullable<int> Lane3 { get; set; }
        public Nullable<int> Lane4 { get; set; }
        public Nullable<int> Lane5 { get; set; }
        public Nullable<int> Lane6 { get; set; }
        public System.DateTime Date { get; set; }
        public int TimeId { get; set; }
    
        public virtual DayTimeSet DayTimeSet { get; set; }
        public virtual TrainingGroup TrainingGroup { get; set; }
        public virtual TrainingGroup TrainingGroup1 { get; set; }
        public virtual TrainingGroup TrainingGroup2 { get; set; }
        public virtual TrainingGroup TrainingGroup3 { get; set; }
        public virtual TrainingGroup TrainingGroup4 { get; set; }
        public virtual TrainingGroup TrainingGroup5 { get; set; }
    }
}
