//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poolAdminMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class poolDBEntities : DbContext
    {
        public poolDBEntities()
            : base("name=poolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonement> Abonements { get; set; }
        public virtual DbSet<CalendarTimeRow> CalendarTimeRows { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<DayTimeSet> DayTimeSets { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesPosition> EmployeesPositions { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<TrainingGroup> TrainingGroups { get; set; }
        public virtual DbSet<VisitDate> VisitDates { get; set; }
        public virtual DbSet<VisitType> VisitTypes { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<Renter> Renters { get; set; }
    }
}
