//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poolAdminMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitDate
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> AbonementId { get; set; }
        public int ClientId { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Client Client { get; set; }
    }
}
